### ISSUE TITLE
ModeModal Video Bug

### ISSUE THREAD

**Issue by CrEaK** [tonisalae/TSMiniWebBrowser#2]
When you open a youtube-video in the browser (TSMiniWebBrowserModeModal) and close it afterwards, the browser is closed with weird graphic glitches leftover and you cannot open the browser or other views with modalMode. You must restart the app.

**Comment by tonisalae** [comment]
Hello @CrEaK ,

Could you provide an example of URL that produces the problem?

Thank you very much.

**Comment by CrEaK** [comment]
on this site the error appears:
http://www.xrel.to/movie/72308/Black-Gold.html#video=_KLQjS7egS4

Thanks for your help!

**Comment by tonisalae** [comment]
Sorry for the delay @CrEaK ,

The problem is not a trivial one. In this stackoverflow topic you have the problem and a possible workaround: 

http://stackoverflow.com/questions/8419145/playing-youtube-video-inside-uiwebview-how-to-handle-the-done-button/9129304#9129304

As you can see, I can't solve the problem from inside TSMiniWebBrowser because the problem is related to how iOS manages modal view controllers and the youtube modal view.

I'm currently working on an example that uses this workaround. I will update the repository soon.

Sorry for the inconvenience.

**Comment by CrEaK** [comment]
no problem, thanks a lot for the help. 
im not at home right now to try out the workaround, but i will test it later.

anyway, thanks for this browser, its so easy to use and i found out yesterday it also works for the ipad, very nice! Looking forward to work more with the browser :)

**Comment by tonisalae** [comment]
Hello again,

Sorry for the delay. I have just uploaded a new project example that uses the workaround provided previously. You will find it in the "MoreDemos" folder.

Please @CrEaK , could you check if it works for you? If everything is ok, the issue may be closed.

Thank you very much.

**Comment by CrEaK** [comment]
Sorry, i was on vacation.

I close the issue, the workaround is working for me. 

Thanks a lot for the help!
